#!/usr/bin/env bash
#-*- mode: sh -*-

export PROJECT_ROOT=$(pwd)
export PATH=$PROJECT_ROOT/env:$PATH

function build() {
    if [ ! -f env/build ]; then
        mkdir -p env/build
    fi

    gcc -std=c99 -pedantic-errors -fextended-identifiers -g -x c -o env/build/client client.c
    gcc -std=c99 -pedantic-errors -fextended-identifiers -g -x c -o env/build/server server.c
}

function client() {
    if [ -f env/build/client ]; then
        env/build/client
    fi
}

function server() {
    if [ -f env/build/server ]; then
        env/build/server
    fi
}
