#!/usr/bin/env bash
#-*- mode: sh -*-

export PROJECT_ROOT=$(pwd)
export PATH=$PROJECT_ROOT/env:$PATH

function build() {
    if [ ! -f env/build ]; then
        mkdir -p env/build
    fi

    gcc -std=c99 -pedantic-errors -fextended-identifiers -g -x c -o env/build/run main.c -lm
}

function run() {
    if [ -f env/build/run ]; then
        sudo env/build/run
    fi
}
